### ISSUE TITLE
CVM System Crash During INT 80 Injection in SSH Attack

### ISSUE THREAD

**Issue by yaoyue123** [ahoi-attacks/heckler#1]
When attempting to perform the SSH attack by injecting INT 80, I noticed that the Confidential VM (CVM) system crashes instead of successfully bypassing the SSH authentication. The system becomes unresponsive rather than achieving the expected authentication bypass.

Steps to reproduce:
1. Set up the attack environment as described
2. Attempt to inject INT 80 during SSH connection
3. Result: CVM crashes instead of bypassing authentication

Could you please provide any insights on:
- Is this a known behavior?
- Are there any specific parameters or timing considerations I should be aware of?
- Any suggestions for troubleshooting this issue?

**Comment by abertschi** [comment]
Hello, the accuracy of the attack is subject to its offline analysis. This
requires you to create page traces of sudo and ssh for your particular CVM setup
and fine tune the attack. See Heckler Paper [0] "offline phase" in 7.3 "Finding a
Function", 8.2, 8.3, 8.5.

I suggest you start with the sudo attack as the page trace pattern (ping pong)
is simpler to verify and detect.

Here are some pointers to get your started:

pattern: https://github.com/ahoi-attacks/heckler/blob/master/userspace/attack/heckler/sudo/sudo_attack.py#L239
tests: https://github.com/ahoi-attacks/heckler/blob/master/userspace/attack/tests/test_sudo.py

[0] https://ahoi-attacks.github.io/heckler/heckler_usenix24.pdf

**Comment by yaoyue123** [comment]
Thank you for your response. I have successfully reproduced the sudo attack scenario. To better understand and analyze the SSH attack implementation, would it be possible for you to provide a pre-configured qcow2 image file with the SSH attack environment? This would be extremely helpful for my further research. I would greatly appreciate it if you could share this.
